config/routes.rb
Rails.application.routes.draw do
  
  resources :gossips
  root"gossips#index"

  get "gossips/new"

  get "gossips/edit"

  get "gossips/show"

  end
  

app/models/gossip.rb
class Gossip < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
	def index
	end
	
	def new
	@gossip = Gossip.new
	end
	
	def create
		gossip = Gossip.create(gossip_params)
	
	redirect_to gossip_path(gossip.id)
	end
	def show
  @gossip = Gossip.find(params[:id])
	end

end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/index.html.erb
<h1> bojour </h1>

app/views/gossips/new.html.erb
<h1> Hello, Welcome to Gossip Land!! </h1>

<h1> Creer un gossip</h1>
<%= form_tag (gossips_path) do %>
<%= label_tag 'author', 'auteur' %>
    <%= text_field_tag 'author' %>
    <%= label_tag 'content', 'ton gossip' %>
    <%= text_field_tag 'author' %>
    <%= submit_tag "Poster un gossip"%>
<% end %>

<p> whatsup </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheGossipProjects</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>